Modern Development Practices/Semantic Similarity/Examples/nlp_proj/faq_app/urls.py
from django.urls import path
from . import views

app_name = 'faq_app'

urlpatterns = [
    path('', views.faq, name='faq'),
    path('ask/', views.ask_question, name='ask_question'),
]

Modern Development Practices/Semantic Similarity/Examples/nlp_proj/nlp_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('faq/', include('faq_app.urls'))
]

Modern Development Practices/Semantic Similarity/Examples/nlp_proj/faq_app/models.py
from django.db import models

# Create your models here.

Modern Development Practices/Semantic Similarity/Examples/nlp_proj/faq_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .functions import faq_detection

# Create your views here.
def faq(request):
    return render(request, 'faq.html')


def ask_question(request):
    user_question = request.POST['question']
    with open('faq_app/data/faq.txt', 'r', encoding='utf-8') as file:
        faq_detector = faq_detection.FAQDetector(file)
    question, answer = faq_detector.get_most_similar_question(user_question)
    return render(request, 'answer.html', {'question':question, 'answer':answer})

Modern Development Practices/Semantic Similarity/Examples/nlp_proj/faq_app/templates/answer.html
<!DOCTYPE html>
<html>
<head>
    <title>Q&A Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #f7f7f7;
        }

        #container {
            width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        }

        h1 {
            color: #333;
        }

        #question {
            font-size: 24px;
            margin: 20px 0;
        }

        #answer {
            font-size: 18px;
            margin: 20px 0;
        }

        #ask-again-button {
            background-color: #4CAF50;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            border-radius: 4px;
        }

        #ask-again-button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div id="container">
        <h1>Question & Answer</h1>
        <div id="question">
            <strong>Q: {{ question }}</strong>
        </div>
        <div id="answer">
            <p>A: {{ answer }}</p>
        </div>
        <a href="{% url 'faq_app:faq' %}"><button id="ask-again-button">Ask Again</button></a>
    </div>
</body>
</html>

Modern Development Practices/Semantic Similarity/Examples/nlp_proj/faq_app/templates/faq.html
<!DOCTYPE html>
<html>
<head>
    <title>Ask a Question</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #f7f7f7;
        }

        #container {
            width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        }

        h1 {
            color: #333;
        }

        #question {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 20px;
        }

        #ask-button {
            background-color: #4CAF50;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            border-radius: 4px;
        }

        #ask-button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div id="container">
        <h1>Ask a Question</h1>
        <form id="question-form" action="{% url 'faq_app:ask_question' %}" method="post">
            {% csrf_token %}
            <input type="text" id="question" name="question" placeholder="Type your question here" autocomplete="off">
            <button type="submit" id="ask-button">Ask</button>
        </form>
    </div>
</body>
</html>