Modern Development Practices/Django/Examples/my_django_proj/my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sport_app/', include('sport_app.urls')),
]

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/urls.py
from django.urls import path
from . import views


app_name = 'sport_app'
urlpatterns = [
    path('', views.login_landing, name="login"),
    path("login_user/", views.login_user, name="login_user"),
    path("logout_user/", views.logout_user, name="logout"),
    path('register/', views.register, name="register"),
    path('register_user/', views.register_user, name="register_user"),
    path('welcome', views.welcome, name="welcome"),
    path('register_team', views.register_team),
    path('add_team/', views.add_team),
    path('register_player', views.register_player),
    path('add_player/', views.add_player),
]

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/models.py
from typing import Any
from django.db import models

# Create your models here.
class FootballTeam(models.Model):
    
    team_registration_key = models.CharField(max_length=5, primary_key=True)
    team_name = models.CharField(max_length=20)
    total_registered_players = models.IntegerField()

class RugbyTeam(models.Model):
    
    team_registration_key = models.CharField(max_length=5, primary_key=True)
    team_name = models.CharField(max_length=20)
    total_registered_players = models.IntegerField()

class TrackAthlete(models.Model):
    
    player_registration_key = models.CharField(max_length=5, primary_key=True)
    player_name = models.CharField(max_length=20)
    player_surname = models.CharField(max_length=20)
    player_age = models.IntegerField()

class TennisPlayer(models.Model):
    
    player_registration_key = models.CharField(max_length=5, primary_key=True)
    player_name = models.CharField(max_length=20)
    player_surname = models.CharField(max_length=20)
    player_age = models.IntegerField()

class GolfPlayer(models.Model):
    
    player_registration_key = models.CharField(max_length=5, primary_key=True)
    player_name = models.CharField(max_length=20)
    player_surname = models.CharField(max_length=20)
    player_age = models.IntegerField()

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from . import models

# Create your views here.
def login_landing(request):
    return render(request, 'login.html')

def login_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(reverse("sport_app:login"))
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('sport_app:welcome')
        )

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("sport_app:login"))

def register(request):
    return render(request, 'register.html')

def register_user(request):
    user_form = request.POST
    if (user_form.get('username') and user_form.get('password')
        and user_form.get('password') == user_form.get('password_conf')):
            user = User.objects.create_user(username=user_form.get('username'), password=user_form.get('password'))
            user.save()
            return render(request, 'user_register_success.html')
    return HttpResponseRedirect(reverse("sport_app:register"))

@login_required(login_url="/sport_app/")
def welcome(request):
    return render(request, 'welcome.html')

@login_required(login_url="/sport_app/")
def register_team(request):
    sport = request.GET['sport']
    return render(request, 'team_register.html', {'sport' : sport})

def add_team(request):
    model_dict = {
        'football' : models.FootballTeam,
        'rugby' : models.RugbyTeam
    }
    sport = request.POST.get('sport')
    # print(sport)
    if sport in model_dict:
        sport = model_dict[sport]()
    sport.team_registration_key = request.POST.get('registrationCode')
    sport.team_name = request.POST.get('teamName')
    sport.total_registered_players = request.POST.get('totalPlayers')
    sport.save()
    return render(request, 'team_added.html')

@login_required(login_url="/sport_app/")
def register_player(request):
    sport = request.GET['sport']
    return render(request, 'player_register.html', {'sport' : sport})

def add_player(request):
    model_dict = {
        'track' : models.TrackAthlete,
        'tennis' : models.TennisPlayer,
        'golf' : models.GolfPlayer
    }
    sport = request.POST.get('sport')
    print(sport)
    if sport in model_dict:
        sport = model_dict[sport]()
    sport.player_registration_key = request.POST.get('registrationCode')
    sport.player_name = request.POST.get('playerName')
    sport.player_surname = request.POST.get('playerSurname')
    sport.player_age = request.POST.get('playerAge')
    sport.save()
    return render(request, 'player_added.html')

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/added.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/welcome_style.css' %}">
    <title>Success</title>
</head>
<body>
    {% block header %}
    {% endblock %}
    <div class="container mt-5">
        <div class="login-form">
            <form action="">
                <button type="submit" class="btn btn-primary btn-login">Home</button>
            </form>
        </div>
    </div>
</body>
</html>

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/landing_template.html
{% load static %}

{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    
    <!-- Link to Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style/login_style.css' %}">

</head>
<body>

<div class="container mt-5">
    <div class="login-form">
        <h2>Login</h2>
        <form action="{% url 'sport_app:login_user' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control" name="username" autocomplete="off" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary btn-login">Login</button>
        </form>
    </div>
</div>
<div class="container mt-5">
    <div class="login-form">
        <form action="{% url 'sport_app:register' %}">
            Don't have an account?
            <button type="submit" class="btn btn-primary btn-login">Register</button>
        </form>
    </div>
</div>


</body>
</html>

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/player_added.html
{% extends 'added.html' %}
{% block header %}
<header>Player successfully added!</header>
{% endblock %}

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/player_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Your Team</title>
    <!-- Link to Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* Add custom CSS styles here, if needed */
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="mb-4">Add Your Team</h2>
                <form action="add_player/" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="playerName">Player Name</label>
                        <input type="text" class="form-control" name="playerName" placeholder="Player Name" required>
                    </div>
                    <div class="form-group">
                        <label for="playerSurname">Player Surname</label>
                        <input type="text" class="form-control" name="playerSurname" placeholder="Player Surname" required>
                    </div>
                    <div class="form-group">
                        <label for="totalPlayers">Player Age</label>
                        <input type="number" class="form-control" name="playerAge" placeholder="Player Age" required>
                    </div>
                    <div class="form-group">
                        <label for="registrationCode">Registration Code</label>
                        <input type="text" class="form-control" name="registrationCode" placeholder="Enter Registration Code" required>
                    </div>
                    <input type="hidden" name="sport" value="{{ sport }}">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Form</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style/login_style.css' %}">

</head>
<body>

<div class="container mt-5">
    <div class="login-form">
        <h2>Register</h2>
        <form action="{% url 'sport_app:register_user' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control" name="username" autocomplete="off" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password" required>
            </div>
            <div class="form-group">
                <label for="password">Confirm Password:</label>
                <input type="password" class="form-control" name="password_conf" required>
            </div>
            <button type="submit" class="btn btn-primary btn-login">Register</button>
            <a href="{% url 'sport_app:login' %}" class="btn btn-primary">Login</a>
        </form>
    </div>
</div>

</body>
</html>

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/team_added.html
{% extends 'added.html' %}
{% block header %}
<header>Team successfully added!</header>
{% endblock %}

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/team_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Your Team</title>
    <!-- Link to Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="mb-4">Add Your Team</h2>
                <form action="add_team/" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="teamName">Team Name</label>
                        <input type="text" class="form-control" name="teamName" placeholder="Enter Team Name" required>
                    </div>
                    <div class="form-group">
                        <label for="totalPlayers">Total Registered Players</label>
                        <input type="number" class="form-control" name="totalPlayers" placeholder="Enter Total Players" required>
                    </div>
                    <div class="form-group">
                        <label for="registrationCode">Registration Code</label>
                        <input type="text" class="form-control" name="registrationCode" placeholder="Enter Registration Code" required>
                    </div>
                    <input type="hidden" name="sport" value="{{ sport }}">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/user_register_success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/welcome_style.css' %}">
    <title>Success</title>
</head>
<body>
    <header>User successfully added!</header>
    <div class="container mt-5">
        <div class="login-form">
            <form action="{% url 'sport_app:login' %}">
                <button type="submit" class="btn btn-primary btn-login">Login</button>
            </form>
        </div>
    </div>
</body>
</html>

Modern Development Practices/Django/Examples/my_django_proj/my_project/sport_app/templates/welcome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/welcome_style.css' %}">
    <title>Choose a Sport</title>
</head>
<body>
    <header>Please choose a sport:</header>
    <div class="sport-options">
        <a href="register_team?sport=football" class="sport-option">
            <img src="{% static 'assets/football.jpg' %}" alt="Football" class="sport-image">
            Football
        </a>
        <a href="register_team?sport=rugby" class="sport-option">
            <img src="{% static 'assets/rugby.jpg' %}" alt="Rugby" class="sport-image">
            Rugby
        </a>
        <a href="register_player?sport=track" class="sport-option">
            <img src="{% static 'assets/track.jpg' %}" alt="Track" class="sport-image">
            Track
        </a>
        <a href="register_player?sport=tennis" class="sport-option">
            <img src="{% static 'assets/tennis.jpg' %}" alt="Tennis" class="sport-image">
            Tennis
        </a>
        <a href="register_player?sport=golf" class="sport-option">
            <img src="{% static 'assets/golf.jpg' %}" alt="Golf" class="sport-image">
            Golf
        </a>
    </div>
</body>
</html>